spring:
  config:
    import: config/import/import_my.yml
#spring:
#  config:
#    import:
#      # 导入classpath下default目录下的default.properties配置文件
#      - classpath:/default/default.properties
#      # 导入classpath下service目录下的service.yml配置文件
#      - classpath:/service/service.yml
com:
  rookie:
    bigdata:
      spring:
        application:
          dev: application-dev
